use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::Path;

use base64::Engine;
use base64::engine::general_purpose::STANDARD;
use serde::Deserialize;

// ---------------------------------------------------------------------------
// Models JSON schema
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct ModelTokens {
    content_multiplier: f64,
    base_overhead: i32,
    per_message: i32,
    tools_exist: i32,
    per_tool: i32,
    per_desc: i32,
    per_first_prop: i32,
    per_additional_prop: i32,
    per_prop_desc: i32,
    per_enum: i32,
    per_nested_object: i32,
    per_array_of_objects: i32,
}

#[derive(Deserialize)]
struct ModelPricing {
    input: f64,
    output: f64,
    #[serde(default)]
    input_cache_read: Option<f64>,
    #[serde(default)]
    input_cache_write: Option<f64>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct ModelConfig {
    encoding: String,
    tokens: ModelTokens,
    name: String,
    context_window: u64,
    max_tokens: u64,
    #[serde(default)]
    pricing: Option<ModelPricing>,
}

// ---------------------------------------------------------------------------
// Claude JSON schema
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
struct ClaudeJsonData {
    pat_str: String,
    special_tokens: HashMap<String, u32>,
    bpe_ranks: String,
}

// ---------------------------------------------------------------------------
// Codegen helpers
// ---------------------------------------------------------------------------

fn fmt_f64(v: f64) -> String {
    // {:?} outputs shortest round-trip representation
    format!("{:?}", v)
}

fn fmt_opt_f64(v: Option<f64>) -> String {
    match v {
        Some(val) => format!("Some({:?})", val),
        None => "None".to_string(),
    }
}

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = env::var("OUT_DIR").unwrap();
    let data_dir = Path::new(&manifest_dir).join("data");

    generate_models(&data_dir, &out_dir);
    generate_claude_bpe(&data_dir, &out_dir);

    println!("cargo::rerun-if-changed=data/models.json");
    println!("cargo::rerun-if-changed=data/claude.json");
}

// ---------------------------------------------------------------------------
// Models codegen
// ---------------------------------------------------------------------------

fn generate_models(data_dir: &Path, out_dir: &str) {
    let json = fs::read_to_string(data_dir.join("models.json")).unwrap();
    let models: HashMap<String, ModelConfig> = serde_json::from_str(&json).unwrap();

    let mut sorted: Vec<_> = models.iter().collect();
    sorted.sort_by_key(|(k, _)| k.as_str());

    let mut out = String::with_capacity(64 * 1024);
    out.push_str("// Generated by build.rs — do not edit\n\n");
    out.push_str(
        "pub(crate) fn init_models() -> Vec<(&'static str, super::ModelConfig)> {\n    vec![\n",
    );

    for (id, c) in &sorted {
        let pricing = match &c.pricing {
            Some(p) => format!(
                "Some(super::ModelPricing {{ input: {}, output: {}, input_cache_read: {}, input_cache_write: {} }})",
                fmt_f64(p.input),
                fmt_f64(p.output),
                fmt_opt_f64(p.input_cache_read),
                fmt_opt_f64(p.input_cache_write),
            ),
            None => "None".to_string(),
        };

        out.push_str(&format!(
            "\
        ({id:?}, super::ModelConfig {{
            encoding: {enc:?}.to_string(),
            tokens: super::ModelTokens {{
                content_multiplier: {cm},
                base_overhead: {bo},
                per_message: {pm},
                tools_exist: {te},
                per_tool: {pt},
                per_desc: {pd},
                per_first_prop: {pfp},
                per_additional_prop: {pap},
                per_prop_desc: {ppd},
                per_enum: {pe},
                per_nested_object: {pno},
                per_array_of_objects: {pao},
            }},
            name: {name:?}.to_string(),
            context_window: {cw},
            max_tokens: {mt},
            pricing: {pricing},
        }}),\n",
            id = id,
            enc = c.encoding,
            cm = fmt_f64(c.tokens.content_multiplier),
            bo = c.tokens.base_overhead,
            pm = c.tokens.per_message,
            te = c.tokens.tools_exist,
            pt = c.tokens.per_tool,
            pd = c.tokens.per_desc,
            pfp = c.tokens.per_first_prop,
            pap = c.tokens.per_additional_prop,
            ppd = c.tokens.per_prop_desc,
            pe = c.tokens.per_enum,
            pno = c.tokens.per_nested_object,
            pao = c.tokens.per_array_of_objects,
            name = c.name,
            cw = c.context_window,
            mt = c.max_tokens,
            pricing = pricing,
        ));
    }

    out.push_str("    ]\n}\n");
    fs::write(Path::new(out_dir).join("models_generated.rs"), out).unwrap();
}

// ---------------------------------------------------------------------------
// Claude BPE codegen
// ---------------------------------------------------------------------------

fn generate_claude_bpe(data_dir: &Path, out_dir: &str) {
    let json = fs::read_to_string(data_dir.join("claude.json")).unwrap();
    let data: ClaudeJsonData = serde_json::from_str(&json).unwrap();

    // Decode all base64 BPE tokens → compact binary:
    //   repeated [rank: u32 LE][len: u16 LE][token_bytes...]
    let mut bin = Vec::with_capacity(1024 * 1024);
    let mut token_count: u32 = 0;

    for line in data.bpe_ranks.split('\n').filter(|l| !l.is_empty()) {
        let parts: Vec<&str> = line.split(' ').collect();
        if parts.len() < 3 {
            continue;
        }
        let offset: u32 = parts[1].parse().unwrap();
        for (i, b64) in parts[2..].iter().enumerate() {
            let bytes = STANDARD.decode(b64).unwrap();
            let rank = offset + i as u32;
            bin.extend_from_slice(&rank.to_le_bytes());
            bin.extend_from_slice(&(bytes.len() as u16).to_le_bytes());
            bin.extend_from_slice(&bytes);
            token_count += 1;
        }
    }

    fs::write(Path::new(out_dir).join("claude_bpe.bin"), &bin).unwrap();

    // Generate Rust source with Claude metadata
    let mut out = String::with_capacity(1024);
    out.push_str("// Generated by build.rs — do not edit\n\n");
    out.push_str(&format!(
        "pub(crate) const CLAUDE_PAT_STR: &str = {:?};\n\n",
        data.pat_str
    ));
    out.push_str(&format!(
        "pub(crate) const CLAUDE_TOKEN_COUNT: u32 = {token_count};\n\n"
    ));
    out.push_str("pub(crate) const CLAUDE_SPECIAL_TOKENS: &[(&str, u32)] = &[\n");

    let mut specials: Vec<_> = data.special_tokens.iter().collect();
    specials.sort_by_key(|(_, v)| *v);
    for (k, v) in &specials {
        out.push_str(&format!("    ({k:?}, {v}),\n"));
    }
    out.push_str("];\n\n");

    out.push_str(
        "pub(crate) const CLAUDE_BPE_DATA: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/claude_bpe.bin\"));\n",
    );

    fs::write(Path::new(out_dir).join("claude_generated.rs"), out).unwrap();
}
