//! Mirror of the chat-completion response types from `async-openai` 0.36.1, with every
//! non-trivial struct/enum wrapped in [`WithOtherFields`] so unknown JSON fields survive a
//! deserialize → serialize round trip.
//!
//! This file is intentionally self-contained: it does not depend on `async_openai`. The wire
//! format aims to be byte-for-byte compatible with the OpenAI chat completions REST API.

use std::ops::{Deref, DerefMut};

use llmy_types::other::{OtherFields, WithOtherFields};
use serde::{Deserialize, Serialize};

// Shared types defined in req.rs (request side) but used in responses.
pub use crate::req::{
    ChatCompletionMessageCustomToolCall, ChatCompletionMessageToolCall,
    ChatCompletionMessageToolCalls, ChatCompletionMessageToolCallsRaw, CustomTool, FunctionCall,
    FunctionCallRaw, Role, ServiceTier,
};

// ---------------------------------------------------------------------------
// FinishReason
// ---------------------------------------------------------------------------

#[derive(Debug, Serialize, Deserialize, Clone, Copy, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum FinishReason {
    Stop,
    Length,
    ToolCalls,
    ContentFilter,
    FunctionCall,
}

#[derive(Debug, Serialize, Deserialize, Clone, Copy, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum CompletionFinishReason {
    Stop,
    Length,
    ContentFilter,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum FunctionType {
    Function,
}

// ---------------------------------------------------------------------------
// Logprobs
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct TopLogprobsRaw {
    /// The token.
    pub token: String,
    /// The log probability of this token.
    pub logprob: f32,
    /// A list of integers representing the UTF-8 bytes representation of the token.
    pub bytes: Option<Vec<u8>>,
}
pub type TopLogprobs = WithOtherFields<TopLogprobsRaw>;

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct ChatCompletionTokenLogprobRaw {
    /// The token.
    pub token: String,
    /// The log probability of this token, if it is within the top 20 most likely tokens.
    pub logprob: f32,
    /// A list of integers representing the UTF-8 bytes representation of the token.
    pub bytes: Option<Vec<u8>>,
    /// List of the most likely tokens and their log probability, at this token position.
    pub top_logprobs: Vec<TopLogprobs>,
}
pub type ChatCompletionTokenLogprob = WithOtherFields<ChatCompletionTokenLogprobRaw>;

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct ChatChoiceLogprobsRaw {
    /// A list of message content tokens with log probability information.
    pub content: Option<Vec<ChatCompletionTokenLogprob>>,
    pub refusal: Option<Vec<ChatCompletionTokenLogprob>>,
}
pub type ChatChoiceLogprobs = WithOtherFields<ChatChoiceLogprobsRaw>;

// ---------------------------------------------------------------------------
// Response message types
// ---------------------------------------------------------------------------

#[derive(Debug, Serialize, Deserialize, Default, Clone, PartialEq)]
pub struct ChatCompletionResponseMessageAudioRaw {
    /// Unique identifier for this audio response.
    pub id: String,
    /// The Unix timestamp (in seconds) for when this audio response will no longer be accessible.
    pub expires_at: u64,
    /// Base64 encoded audio bytes generated by the model, in the format specified in the request.
    pub data: String,
    /// Transcript of the audio generated by the model.
    pub transcript: String,
}
pub type ChatCompletionResponseMessageAudio =
    WithOtherFields<ChatCompletionResponseMessageAudioRaw>;

#[derive(Debug, Serialize, Deserialize, Default, Clone, PartialEq)]
pub struct UrlCitationRaw {
    /// The index of the last character of the URL citation in the message.
    pub end_index: u32,
    /// The index of the first character of the URL citation in the message.
    pub start_index: u32,
    /// The title of the web resource.
    pub title: String,
    /// The URL of the web resource.
    pub url: String,
}
pub type UrlCitation = WithOtherFields<UrlCitationRaw>;

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ChatCompletionResponseMessageAnnotationRaw {
    UrlCitation { url_citation: UrlCitation },
}
pub type ChatCompletionResponseMessageAnnotation =
    WithOtherFields<ChatCompletionResponseMessageAnnotationRaw>;

/// A chat completion message generated by the model.
#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct ChatCompletionResponseMessageRaw {
    /// The contents of the message.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    /// The refusal message generated by the model.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub refusal: Option<String>,
    /// The tool calls generated by the model, such as function calls.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ChatCompletionMessageToolCalls>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub annotations: Option<Vec<ChatCompletionResponseMessageAnnotation>>,

    /// The role of the author of this message.
    pub role: Role,

    /// Deprecated and replaced by `tool_calls`.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[deprecated]
    pub function_call: Option<FunctionCall>,

    /// If the audio output modality is requested, this object contains data about the audio response.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub audio: Option<ChatCompletionResponseMessageAudio>,
}
pub type ChatCompletionResponseMessage = WithOtherFields<ChatCompletionResponseMessageRaw>;

// ---------------------------------------------------------------------------
// Usage / token details
// ---------------------------------------------------------------------------

/// Breakdown of tokens used in a completion.
#[derive(Debug, Deserialize, Serialize, Clone, PartialEq, Default)]
pub struct CompletionTokensDetailsRaw {
    pub accepted_prediction_tokens: Option<u32>,
    /// Audio input tokens generated by the model.
    pub audio_tokens: Option<u32>,
    /// Tokens generated by the model for reasoning.
    pub reasoning_tokens: Option<u32>,
    /// When using Predicted Outputs, the number of tokens in the prediction that did not appear
    /// in the completion.
    pub rejected_prediction_tokens: Option<u32>,
}
pub type CompletionTokensDetails = WithOtherFields<CompletionTokensDetailsRaw>;

/// Breakdown of tokens used in a prompt.
#[derive(Debug, Deserialize, Serialize, Clone, PartialEq, Default)]
pub struct PromptTokensDetailsRaw {
    /// Audio input tokens present in the prompt.
    pub audio_tokens: Option<u32>,
    /// Cached tokens present in the prompt, i.e. read from the cache.
    pub cached_tokens: Option<u32>,
    /// The unadjusted number of prompt tokens written to cache (GPT-5.6+).
    /// Disjoint from `cached_tokens`; billed at the model's cache-write rate
    /// (1.25x the uncached input rate on GPT-5.6).
    pub cache_write_tokens: Option<u32>,
}
pub type PromptTokensDetails = WithOtherFields<PromptTokensDetailsRaw>;

/// Usage statistics for the completion request.
#[derive(Debug, Deserialize, Serialize, Clone, PartialEq, Default)]
pub struct CompletionUsageRaw {
    /// Number of tokens in the prompt.
    pub prompt_tokens: u32,
    /// Number of tokens in the generated completion.
    pub completion_tokens: u32,
    /// Total number of tokens used in the request (prompt + completion).
    pub total_tokens: u32,
    /// Breakdown of tokens used in the prompt.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prompt_tokens_details: Option<PromptTokensDetails>,
    /// Breakdown of tokens used in a completion.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completion_tokens_details: Option<CompletionTokensDetails>,
}
pub type CompletionUsage = WithOtherFields<CompletionUsageRaw>;

// ---------------------------------------------------------------------------
// ChatChoice / response
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct ChatChoiceRaw {
    /// The index of the choice in the list of choices.
    pub index: u32,
    pub message: ChatCompletionResponseMessage,
    /// The reason the model stopped generating tokens.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub finish_reason: Option<FinishReason>,
    /// Log probability information for the choice.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub logprobs: Option<ChatChoiceLogprobs>,
}
pub type ChatChoice = WithOtherFields<ChatChoiceRaw>;

/// Represents a chat completion response returned by model, based on the provided input.
#[allow(deprecated)]
#[derive(Debug, Deserialize, Clone, PartialEq, Serialize)]
pub struct CreateChatCompletionResponseRaw {
    /// A unique identifier for the chat completion.
    pub id: String,
    /// A list of chat completion choices. Can be more than one if `n` is greater than 1.
    pub choices: Vec<ChatChoice>,
    /// The Unix timestamp (in seconds) of when the chat completion was created.
    pub created: u32,
    /// The model used for the chat completion.
    pub model: String,
    /// The service tier used for processing the request.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub service_tier: Option<ServiceTier>,
    /// This fingerprint represents the backend configuration that the model runs with.
    #[deprecated]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_fingerprint: Option<String>,
    /// The object type, which is always `chat.completion`.
    pub object: String,
    pub usage: Option<CompletionUsage>,
}
pub type CreateChatCompletionResponse = WithOtherFields<CreateChatCompletionResponseRaw>;

// ---------------------------------------------------------------------------
// Stream types
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct FunctionCallStreamRaw {
    /// The name of the function to call.
    pub name: Option<String>,
    /// The arguments to call the function with, as generated by the model in JSON format.
    pub arguments: Option<String>,
}
pub type FunctionCallStream = WithOtherFields<FunctionCallStreamRaw>;

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct ChatCompletionMessageToolCallChunkRaw {
    pub index: u32,
    /// The ID of the tool call.
    pub id: Option<String>,
    /// The type of the tool. Currently, only `function` is supported.
    pub r#type: Option<FunctionType>,
    pub function: Option<FunctionCallStream>,
}
pub type ChatCompletionMessageToolCallChunk =
    WithOtherFields<ChatCompletionMessageToolCallChunkRaw>;

/// A chat completion delta generated by streamed model responses.
#[allow(deprecated)]
#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct ChatCompletionStreamResponseDeltaRaw {
    /// The contents of the chunk message.
    pub content: Option<String>,
    /// Deprecated and replaced by `tool_calls`.
    #[deprecated]
    pub function_call: Option<FunctionCallStream>,

    pub tool_calls: Option<Vec<ChatCompletionMessageToolCallChunk>>,
    /// The role of the author of this message.
    pub role: Option<Role>,
    /// The refusal message generated by the model.
    pub refusal: Option<String>,
}
pub type ChatCompletionStreamResponseDelta = WithOtherFields<ChatCompletionStreamResponseDeltaRaw>;

#[derive(Debug, Deserialize, Serialize, Clone, PartialEq)]
pub struct ChatChoiceStreamRaw {
    /// The index of the choice in the list of choices.
    pub index: u32,
    pub delta: ChatCompletionStreamResponseDelta,
    /// The reason the model stopped generating tokens.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub finish_reason: Option<FinishReason>,
    /// Log probability information for the choice.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub logprobs: Option<ChatChoiceLogprobs>,
}
pub type ChatChoiceStream = WithOtherFields<ChatChoiceStreamRaw>;

/// Represents a streamed chunk of a chat completion response returned by the model.
#[allow(deprecated)]
#[derive(Debug, Deserialize, Clone, PartialEq, Serialize)]
pub struct CreateChatCompletionStreamResponseRaw {
    /// A unique identifier for the chat completion. Each chunk has the same ID.
    pub id: String,
    /// A list of chat completion choices.
    pub choices: Vec<ChatChoiceStream>,

    /// The Unix timestamp (in seconds) of when the chat completion was created.
    pub created: u32,
    /// The model to generate the completion.
    pub model: String,
    /// The service tier used for processing the request.
    pub service_tier: Option<ServiceTier>,
    /// This fingerprint represents the backend configuration that the model runs with.
    #[deprecated]
    pub system_fingerprint: Option<String>,
    /// The object type, which is always `chat.completion.chunk`.
    pub object: String,

    /// Token usage statistics. Only present when stream_options.include_usage is set.
    pub usage: Option<CompletionUsage>,
}
pub type CreateChatCompletionStreamResponse =
    WithOtherFields<CreateChatCompletionStreamResponseRaw>;

// ---------------------------------------------------------------------------
// Public extensible wrappers (preserved from the old API)
// ---------------------------------------------------------------------------

/// Public wrapper around a [`ChatChoice`] (already a `WithOtherFields` alias).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(transparent)]
pub struct RawExtensibleChatChoice(pub ChatChoice);

impl RawExtensibleChatChoice {
    pub fn new(choice: ChatChoiceRaw) -> Self {
        Self(WithOtherFields::new(choice))
    }

    pub fn from_choice(choice: ChatChoice) -> Self {
        Self(choice)
    }

    pub fn extra(&self) -> &OtherFields {
        &self.0.other
    }

    pub fn extra_mut(&mut self) -> &mut OtherFields {
        &mut self.0.other
    }

    pub fn message_extra(&self) -> &OtherFields {
        &self.0.inner.message.other
    }

    pub fn message_extra_mut(&mut self) -> &mut OtherFields {
        &mut self.0.inner.message.other
    }

    pub fn reasoning_content(&self) -> Option<&str> {
        self.message_extra().get("reasoning_content")?.as_str()
    }

    pub fn into_inner(self) -> ChatChoice {
        self.0
    }
}

impl Deref for RawExtensibleChatChoice {
    type Target = ChatChoice;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl DerefMut for RawExtensibleChatChoice {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}

impl From<ChatChoiceRaw> for RawExtensibleChatChoice {
    fn from(choice: ChatChoiceRaw) -> Self {
        Self::new(choice)
    }
}

impl From<ChatChoice> for RawExtensibleChatChoice {
    fn from(choice: ChatChoice) -> Self {
        Self(choice)
    }
}

impl From<RawExtensibleChatChoice> for ChatChoice {
    fn from(choice: RawExtensibleChatChoice) -> Self {
        choice.0
    }
}

/// Public wrapper around a [`CreateChatCompletionResponse`] (already a `WithOtherFields` alias).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(transparent)]
pub struct RawExtensibleChatCompletionResponse(pub CreateChatCompletionResponse);

impl RawExtensibleChatCompletionResponse {
    pub fn new(response: CreateChatCompletionResponseRaw) -> Self {
        Self(WithOtherFields::new(response))
    }

    pub fn from_response(response: CreateChatCompletionResponse) -> Self {
        Self(response)
    }

    pub fn extra(&self) -> &OtherFields {
        &self.0.other
    }

    pub fn extra_mut(&mut self) -> &mut OtherFields {
        &mut self.0.other
    }

    pub fn into_base(self) -> CreateChatCompletionResponseRaw {
        self.0.inner
    }

    pub fn into_inner(self) -> CreateChatCompletionResponse {
        self.0
    }
}

impl Deref for RawExtensibleChatCompletionResponse {
    type Target = CreateChatCompletionResponse;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl DerefMut for RawExtensibleChatCompletionResponse {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}

impl From<CreateChatCompletionResponseRaw> for RawExtensibleChatCompletionResponse {
    fn from(response: CreateChatCompletionResponseRaw) -> Self {
        Self::new(response)
    }
}

impl From<CreateChatCompletionResponse> for RawExtensibleChatCompletionResponse {
    fn from(response: CreateChatCompletionResponse) -> Self {
        Self(response)
    }
}

impl From<RawExtensibleChatCompletionResponse> for CreateChatCompletionResponse {
    fn from(response: RawExtensibleChatCompletionResponse) -> Self {
        response.0
    }
}
