/// Tests that verify llmy-tokenizer produces identical token IDs to the
/// reference ai-tokenizer JS implementation across all 4 encodings.
///
/// Test data is generated by `ai-tokenizer/scripts/gen-test-data.ts`.
use llmy_tokenizer::{Encoding, encode};
use serde::Deserialize;

#[derive(Deserialize)]
struct TestEntry {
    name: String,
    text: String,
    encodings: Encodings,
}

#[derive(Deserialize)]
struct Encodings {
    cl100k_base: Vec<u32>,
    o200k_base: Vec<u32>,
    p50k_base: Vec<u32>,
    claude: Vec<u32>,
}

fn load_expected() -> Vec<TestEntry> {
    let data = include_str!("expected.json");
    serde_json::from_str(data).expect("parse expected.json")
}

#[test]
fn compare_cl100k_base() {
    for entry in &load_expected() {
        let actual = encode(&entry.text, Encoding::Cl100kBase);
        assert_eq!(
            actual, entry.encodings.cl100k_base,
            "cl100k_base mismatch for {:?} (text={:?})",
            entry.name, entry.text
        );
    }
}

#[test]
fn compare_o200k_base() {
    for entry in &load_expected() {
        let actual = encode(&entry.text, Encoding::O200kBase);
        assert_eq!(
            actual, entry.encodings.o200k_base,
            "o200k_base mismatch for {:?} (text={:?})",
            entry.name, entry.text
        );
    }
}

#[test]
fn compare_p50k_base() {
    for entry in &load_expected() {
        let actual = encode(&entry.text, Encoding::P50kBase);
        assert_eq!(
            actual, entry.encodings.p50k_base,
            "p50k_base mismatch for {:?} (text={:?})",
            entry.name, entry.text
        );
    }
}

#[test]
fn compare_claude() {
    for entry in &load_expected() {
        let actual = encode(&entry.text, Encoding::Claude);
        assert_eq!(
            actual, entry.encodings.claude,
            "claude mismatch for {:?} (text={:?})",
            entry.name, entry.text
        );
    }
}
